spring:
  profiles: base
  # redis配置
  redis:
    # host: localhost
    host: 150.158.172.107
    port: 6379
    database: 0 # Redis数据库索引（默认为0）
    password: Jinzelei+2022
    url: redis://Jinzelei+2022@150.158.172.107:6379
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1  # 连接池中的最小空闲连接
    timeout: PT10S # 连接超时时间（毫秒）

# swagger开关
swagger:
  # 后台管理模块api
  system:
    enable: true
  # 前台门户模块api
  portal:
    enable: true