# 数据库连接
spring:
  profiles: utils
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/blog_sunset?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    # username: root
    # password: 123456

    # url: jdbc:mysql://150.158.172.107:3306/blog_sunset?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    # username: root
    # password: Jinzelei+2022

    url: jdbc:mysql://43.136.180.32:3306/blog_sunset?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: Song
    password: Song@123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

#Mybatis-Plus输出日志
mybatis-plus:
  mapper-locations: classpath:xml/*.xml
  configuration:
    # 日志输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启二级缓存
    cache-enabled: true
